### ISSUE TITLE
Error, more than one new minima found

### ISSUE THREAD

**Issue by allsey87** [AprilRobotics/apriltag#59]
Regarding the `fprintf` in [apriltag_pose.c:435](https://github.com/AprilRobotics/apriltag/blob/3.1.1/apriltag_pose.c#L435) that prints:

> Error, more than one new minima found

How is a user of your library supposed to react to this message? Is this a bug or is it debugging output that can be safely ignored? In the latter case, perhaps this debugging output can be toggled on and off using a member of the `apriltag_detection_info_t`?

**Comment by hwscut** [comment]
When seeing more than one tag to estimate tag_pose, I also get such error. 
waitting for solution.

**Comment by zftan0709** [comment]
`Tag ID: 10
Normalized： 
-1.76278 -0.31017
Translation: 
4.97972  -0.959973 -2.89562
Rotation: 
-0.928616 0.175963 -0.326666
0.13727 0.980855 0.138131
-0.344717 -0.0834289 0.934992

Error, more than one new minimum found.

Tag ID: 10
Normalized： 
-1.76919 -0.31115
Translation: 
-5.06095  0.973719 2.93369
Rotation: 
-0.156745 -0.142866 0.977251
0.0681974 -0.988686 -0.133599
0.985282 0.0457049 0.164715
`
I'm having the same problem and the Tz changes to negative from time to time.

**Comment by C-monC** [comment]
Hi,

I get this error with only one tag in the image. Did anyone figure out the reason for this error?

**Comment by wxmerkt** [comment]
Can you provide a test image where this happens?

**Comment by mpillet** [comment]
Can we reopen this issue please ? I'm facing the same problem with 'Error, more than one new minima found' leading to a wrong reconstruction

**Comment by christian-rauch** [comment]
> Can we reopen this issue please ? 

I think this issue was never closed. So no worries there :-)

> I'm facing the same problem with 'Error, more than one new minima found' leading to a wrong reconstruction. Here is an example where the detection of the tag works but with this error of more than one new minima found.

Is this reproducible with the `apriltag_demo`? Can you provide a jpeg image and potential command-line arguments that cause the issue with the `apriltag_demo`?

**Comment by ggb367** [comment]
Hi @christian-rauch, we're also running into this multiple minima error with this image when estimating the pose of each of the tags: 
![image_raw](https://github.com/AprilRobotics/apriltag/assets/35751246/1c46166b-6ca2-4f58-a31c-f2feabed7620)
Usually one minima is correct while the other is quite incorrect.
We tried to see if we could reproduce the error with aprilrtag_demo with:
`./apriltag_demo -f tagStandard52h13 -i 10 ./image_raw.jpg`
But we don't see a way to estimate the pose with that script.
Let me know if I can provide any additional details to figure this issue out.
Thanks!

**Comment by christian-rauch** [comment]
> We tried to see if we could reproduce the error with aprilrtag_demo with: `./apriltag_demo -f tagStandard52h13 -i 10 ./image_raw.jpg` But we don't see a way to estimate the pose with that script.

Thanks for sharing the example image. The `apriltag_demo` executable only does the tag detection without the pose estimation.

> Let me know if I can provide any additional details to figure this issue out. Thanks!

Can you also provide the camera intrinsics used for the pose estimation? Is the code you use publicly available?

**Comment by ggb367** [comment]
> Is the code you use publicly available?    

The repository is not public, but I can share code snippets as needed

> Can you also provide the camera intrinsics used for the pose estimation?    

See below:
```YAML
image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [661.97625,   0.     , 313.69227,
           0.     , 661.02677, 257.01043,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.054322, -0.183210, 0.001954, -0.002335, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [662.69727,   0.     , 312.00752,   0.     ,
           0.     , 662.65527, 257.08592,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
```
